config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'albums#index'
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end
  resources :albums do
    resources :reviews, only: [:create, :edit, :destroy, :update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews
  validates_presence_of :title, :artist
  validates :release_year, numericality: { only_integer: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = [5, 4, 3, 2, 1]
  belongs_to :user
  belongs_to :album

  validates :rating, inclusion: { in: RATINGS }
end

app/models/track.rb
class Track < ApplicationRecord
  # belongs_to :album
  # has_many :reviews
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :albums
  has_many :reviews

  def admin?
   role == "admin"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!, :ensure_admin!


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admin_users_path
  end

  private
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def user_params
      params.require(:user).permit(:email, :password,
                                   :password_confirmation)
  end

  def ensure_admin!
    unless current_user.admin?
      flash[:notice] = 'Not an admin, user signed out and redirected'
      sign_out current_user

      redirect_to root_path

      return false
    end
  end

end

app/controllers/album_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      notice: 'Board game was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).
        permit(
          :title,
          :artist,
          :release_year
        )
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authorize_user, except: [:index, :show]
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
    @review = @album.reviews.build
    @reviews = @album.reviews
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user
    if @album.save
      flash[:notice] = 'Successfully added album'
      redirect_to albums_path
    else
      flash[:notice] = 'Title and Artist must be filled'
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    @album.title = params[:album][:title]
    @album.artist = params[:album][:artist]
    @album.release_year  = params[:album][:release_year]
    if @album.title.nil? || @album.artist.nil?
      flash[:errors] = "Artist and/or Title cannot be empty "
      render 'edit'
    else
      @album.save
      flash[:success] = "Album updated"
      redirect_to album_path(@album)
    end
  end

  def destroy
    Album.find(params[:id]).destroy
    flash[:success] = "Album Deleted"
    redirect_to root_path
  end

  protected

  def authorize_user
    if !user_signed_in?
      flash[:notice] = "Please Sign in to add a new item"
      redirect_to root_path
    end
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:title, :artist, :release_year, :user_id)
  end
  def user_params
    param.require(:user).permit(:email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  #how to redirect after sign out
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @album = Album.find(review_params[:album_id])
    @review = @album.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      flash[:notice] = "Thanks for your input!"
    else
      flash[:error] = "Something is wrong with your review."
    end
    redirect_to @album
  end

  def edit
    @review = Review.find(params[:id])
    @album = Album.find(params[:album_id])
    render 'albums/reviews/edit'
  end

  def update
    @review = Review.find(params[:id])
    @album = Album.find(params[:album_id])
    @review.review = params[:review][:review]
    @review.rating = params[:review][:rating]
    if @review.review.nil? || @review.rating.nil?
      flash[:errors] = "review and/or rating cannot be empty "
      render 'edit'
    else
      @review.save
      flash[:success] = "review updated"
      redirect_to album_path(@album)
    end
  end

  def destroy
    Review.find(params[:id]).destroy
    flash[:success] = "Review Deleted"
    redirect_to root_path
  end

  private
  def set_album
    @album = Album.find(review_params[:album_id])
  end

  def review_params
    params.require(:review).permit(:rating, :review, :album_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    if current_user.role != 'admin'
      redirect_to root_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  private
  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def user_params
      params.require(:user).permit(:email, :password,
                                   :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<h1> Users </h1>
<% @users.each do |u| %>
    <li><%= u.email %>
    <bold><%= u.role %> </bold>
    <%= link_to "delete #{u.email}", admin_user_path(u), method: :delete,  data: { confirm: "You sure?"} %>
    </li>
  <% end %>

app/views/albums/_flash.html.erb
   <% if flash[:notice] %>
     <p><%= flash[:notice] %></p>
   <% end %>
   <% if flash[:success] %>
     <p><%= flash[:success] %></p>
   <% end %>
   <% if flash[:errors] %>
     <p><%= flash[:errors] %></p>
   <% end %>
 

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :artist %>
    <%= f.text_field :artist %>
    <%= f.label :release_year %>
    <%= f.text_field :release_year %>

    <%= f.submit  %>
<% end %>

app/views/albums/_review.html.erb
<h4>New Review</h4>

<%= form_for([@album, @review]) do |f| %>
  <%= f.label :rating %>
  <%= f.collection_select :rating, Review::RATINGS, :to_s, :to_s %>

  <%= f.label :review %>
  <%= f.text_area :review %>

  <%= f.hidden_field :album_id, value: @album.id %>

  <%= f.submit %>
<% end %>

app/views/albums/_review_display.html.erb
<h2> User Reviews </h2>
  <% if @album.reviews %>
    <% @album.reviews.each do |rev| %>
      <li><%= rev.rating %> <%= rev.review %>
        <% if rev.id.nil? %>
            <%= nil %>
        <% else %>
          -<font color="blue"> <%= rev.user.email %> </font></li>
        <% end %>
        <% if rev.id.nil?%>
          <%= nil %>
        <% elsif rev.user == current_user %>
          <%= link_to 'edit', edit_album_review_path(@album, rev.id) %>
          <%= link_to 'delete', album_review_path(@album, rev.id), method: :delete, data: {confirm: 'You sure?'} %>
        <% end %>
    <% end %>
  <%end%>

app/views/albums/edit.html.erb
<h1>Update Album</h1>

<%= render 'form' %>

app/views/albums/index.html.erb
<h1> Albums </h1>
<%= render 'flash' %>
<div>
<% @albums.each do |album| %>
  <ul>
    <li> <strong><%= link_to album.title , album %></strong>
    </li>
    <span> <%= album.artist %> </span>
    <br>
  </ul>
<% end %>
</div>
<br>
<%= link_to "Add new album", new_album_path %>

app/views/albums/new.html.erb
<h1> Submit New Album For Review </h1>
<%= render 'flash' %>
<%= render 'form' %>

app/views/albums/reviews/edit.html.erb
<h1> Edit Review </h1>

<%= form_for([@album, @review]) do |f| %>
  <%= f.label :rating %>
  <%= f.collection_select :rating, Review::RATINGS, :to_s, :to_s %>

  <%= f.label :review %>
  <%= f.text_area :review %>

  <%= f.hidden_field :album_id, value: @album.id %>

  <%= f.submit %>
<% end %>

app/views/albums/show.html.erb
<div align="center"><h1> <%= @album.title %>  </h1></div>

<div align="center">
  <ul>
  <%= @album.artist %> <br>
  <%= @album.release_year %>
  </ul>
</div>

<div class="reviews">
  <% if user_signed_in? %>
    <%= render 'review' %>
  <% else %>
    <p> Sign in to leave a review </p>
  <% end %>

  <%= render 'review_display' %>
</div>

<div>
  <% if @album.user == current_user %>
    <%= link_to 'edit', edit_album_path %>
    <%= link_to 'delete', album_path, method: :delete,
                                 data: { confirm: "You sure?"} %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "AlbumRev" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>


  <div class="top-bar">
    <% if user_signed_in? %>
      <%= link_to "sign out", destroy_user_session_path, method: :delete %>
      <%= link_to "Edit Account", edit_user_registration_path %>
    <% else %>
      <%= link_to "sign in", new_user_session_path %>
      <%= link_to "sign up", new_user_registration_path %>
    <% end %>
  </div>

  <body>
    <div class="row">
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1> Users </h1>
<% @users.each do |u| %>
    <li><%= u.email %>
    <bold><%= u.role %> </bold>
    <%= link_to "delete #{u.email}", user_path(u), method: :delete,  data: { confirm: "You sure?"} %>
    </li>
  <% end %>